### ISSUE TITLE
Error: Traceback (most recent call last):   File "main.py", line 53, in <module>     run_joiner()   File "main.py", line 49, in run_joiner     joiner(usertoken, status)   File "main.py", line 34, in joiner     ws = websocket.WebSocket() TypeError: WebSocket.__init__() missing 3 required positional arguments: 'environ', 'socket', and 'rfile'

### ISSUE THREAD

**Issue by pashkatate** [SealedSaucer/Voicecord#14]
Successfully logs into my account, but spits out error after initiating `run_joiner()`

**Comment by pashkatate** [comment]
```
Traceback (most recent call last):
  File "main.py", line 82, in <module>
    run_joiner()
  File "main.py", line 77, in run_joiner
    joiner(usertoken, status)
  File "main.py", line 37, in joiner
    ws = websocket.WebSocket()
TypeError: WebSocket.__init__() missing 3 required positional arguments: 'environ', 'socket', and 'rfile'
```

**Comment by BryanAlberts** [comment]
same here

**Comment by pashkatate** [comment]
found a different way of doing it. check my repos for a working one.

**Comment by SealedSaucer** [comment]
@SoundDr0ut @wauv the fix to this issue is already mentioned in the README.md file: [Link](https://github.com/SealedSaucer/Voicecord#replit-typeerror-websocket__init-missing-3-required-positional-arguments-environ-socket-and-rfile)

![image](https://github.com/SealedSaucer/Voicecord/assets/71928730/17fcbf64-b7e9-400d-94cd-ca5637b54153)

Closing the issue.
